[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
http = { version = "1", optional = true }
leptos = "0.8.20"
leptos_axum = { version = "0.8.10", optional = true }
leptos_meta = "0.8.6"
leptos_router = "0.8.15"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false, features = ["sqlite", "runtime-tokio", "macros"], optional = true }
tracing = { version = "0.1.44", optional = true }
wasm-bindgen = { version = "=0.2.126", optional = true }

[features]
hydrate = ["leptos/hydrate", "dep:wasm-bindgen", "dep:console_error_panic_hook"]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:sqlx",
    "dep:tracing",
    "dep:http",
    "dep:leptos_axum",
]
