[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { version = "0.1.0", path = "../app", features = ["ssr"] }
argon2 = "0.5.3"
axum = "0.8.9"
dotenvy = "0.15.7"
leptos = { version = "0.8.20", features = ["ssr"] }
leptos_axum = "0.8.10"
leptos_meta = { version = "0.8.6", features = ["ssr"] }
leptos_router = { version = "0.8.15", features = ["ssr"] }
sqlx = { version = "0.9.0", default-features = false, features = ["sqlite", "runtime-tokio", "migrate", "macros"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net"] }
tower-http = { version = "0.7.0", features = ["catch-panic", "fs"] }
tower-sessions = "0.15.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["sqlite"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
ssr = ["app/ssr", "leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]
